### ISSUE TITLE
Exception when trying to convert Workspace, when multiple identitcly PropertyGroup are present

### ISSUE THREAD

**Issue by Lohnegrim** [dotnet/try-convert#123]
Hi,
I tryed to convert a old project, but the convertion crashed with this Error:
```
System.ArgumentException: An element with the same key but a different value already exists. Key: Debug|AnyCPU
   at System.Collections.Immutable.ImmutableDictionary`2.HashBucket.Add(TKey key, TValue value, IEqualityComparer`1 keyOnlyComparer, IEqualityComparer`1 valueComparer, KeyCollisionBehavior behavior, OperationResult& result)
   at System.Collections.Immutable.ImmutableDictionary`2.Add(TKey key, TValue value, KeyCollisionBehavior behavior, MutationInput origin)
   at MSBuild.Abstractions.MSBuildWorkspace.DetermineConfigurations(IProjectRootElement projectRootElement) in /_/src/MSBuild.Abstractions/MSBuildWorkspace.cs:line 68
   at MSBuild.Abstractions.MSBuildWorkspace..ctor(ImmutableArray`1 paths, Boolean noBackup) in /_/src/MSBuild.Abstractions/MSBuildWorkspace.cs:line 44
   at MSBuild.Abstractions.MSBuildWorkspaceLoader.LoadWorkspace(String path, Boolean noBackup) in /_/src/MSBuild.Abstractions/MSBuildWorkspaceLoader.cs:line 45
   at MSBuild.Conversion.Program.Run(String project, String workspace, String msbuildPath, Boolean diffOnly, Boolean noBackup) in /_/src/try-convert/Program.cs:line 73
```
The reason is found is that one of the projects had the propertygroups definationed multiple times.
e.g.
```xml
 <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Debug|AnyCPU'">
    <DebugSymbols>true</DebugSymbols>
    <DefineDebug>true</DefineDebug>
    <DefineTrace>true</DefineTrace>
    <OutputPath>..\bin\Debug\</OutputPath>
    <DebugType>full</DebugType>
    <PlatformTarget>AnyCPU</PlatformTarget>    
    <WarningsAsErrors>41999,42016,42017,42018,42019,42020,42021,42022,42032,42036</WarningsAsErrors>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Release|AnyCPU'">
    <DefineTrace>true</DefineTrace>
    <OutputPath>..\bin\Release\</OutputPath>
    <Optimize>true</Optimize>
    <DebugType>pdbonly</DebugType>
    <PlatformTarget>AnyCPU</PlatformTarget>    
    <WarningsAsErrors>41999,42016,42017,42018,42019,42020,42021,42022,42032,42036</WarningsAsErrors>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Debug|AnyCPU'">
    <DebugSymbols>true</DebugSymbols>
    <DefineDebug>true</DefineDebug>
    <DefineTrace>true</DefineTrace>
    <OutputPath>..\bin\Debug\</OutputPath>
    <DebugType>full</DebugType>
...
```
It would be nice if these could automaticly merged.
Also if the convertion crashes when converting one project then it would be nice if there is any info about the project currently checked/converted,

**Comment by jmarolf** [comment]
yep we will just need to update this method to handle this case:

https://github.com/dotnet/try-convert/blob/66a1c5e76cd27ba54dc0d42870a49f96fce059e5/src/MSBuild.Abstractions/MSBuildWorkspace.cs#L60-L73

**Comment by RussKie** [comment]
How would you reconcile a situation where duplicate sections have different values?
```xml
 <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Debug|AnyCPU'">
    <DebugSymbols>true</DebugSymbols>
    <DefineDebug>true</DefineDebug>
    <DefineTrace>true</DefineTrace>
    <OutputPath>..\bin\Debug\</OutputPath>
    <DebugType>full</DebugType>
    <PlatformTarget>AnyCPU</PlatformTarget>    
    <WarningsAsErrors>41999,42016,42017,42018,42019,42020,42021,42022,42032,42036</WarningsAsErrors>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Debug|AnyCPU'">
    <DebugSymbols>false</DebugSymbols>					<--- different
    <DefineTrace>true</DefineTrace>
    <OutputPath>..\bin\Debug\</OutputPath>
    <DebugType>auto</DebugType>							<--- different
...
```

**Comment by jmarolf** [comment]
MSBuild works where the last value wins. You just take the last value you see. That's what the project is doing today.
