### ISSUE TITLE
Generic error: This project has custom imports in a manner that's not supported.

### ISSUE THREAD

**Issue by LordBenjamin** [dotnet/try-convert#300]
**Version:** 0.5.125603

Receiving an error message that doesn't seem appropriate:

```
> try-convert -p .\MyProject.csproj

 System.NotSupportedException: This project has custom imports in a manner that's not supported. 'MyProject.csproj'
   at MSBuild.Abstractions.MSBuildWorkspace.CreateSdkBaselineProject(String projectFilePath, IProject project, IProjectRootElement root, ImmutableDictionary`2 configurations) in /_/src/MSBuild.Abstractions/MSBuildWorkspace.cs:line 113
   at MSBuild.Abstractions.MSBuildWorkspace..ctor(ImmutableArray`1 paths, Boolean noBackup) in /_/src/MSBuild.Abstractions/MSBuildWorkspace.cs:line 52
   at MSBuild.Abstractions.MSBuildWorkspaceLoader.LoadWorkspace(String path, Boolean noBackup) in /_/src/MSBuild.Abstractions/MSBuildWorkspaceLoader.cs:line 45
   at MSBuild.Conversion.Program.Run(String project, String workspace, String msbuildPath, String tfm, Boolean allowPreviews, Boolean diffOnly, Boolean noBackup, Boolean keepCurrentTfms) in /_/src/try-convert/Program.cs:line 103
```
But I've tried stripping everything out of the csproj file, until eventually I ended up with:

```xml
<?xml version="1.0" encoding="utf-8"?>
<Project>
  <PropertyGroup>
    <OutputType>Library</OutputType>
  </PropertyGroup>
</Project>
```

Still the same error message though - any ideas?

**Comment by LordBenjamin** [comment]
Update - got it working.

I found I had to add:
```xml
<Import Project="$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props" Condition="Exists('$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props')" />
```
And remove:

```xml
 <Import Project="$(MSBuildExtensionsPath32)\StyleCop\v4.7\StyleCop.Targets" Condition="'$(StyleCopEnabled)' == 'true'" />
```

Removing an unsupported export makes sense given the error message, but I don't think it's at all obvious that you might have to add one!

**Comment by cartermp** [comment]
Good observation. Yeah, there are specific imports that are assumed for an old-style project. This issue tracks listing out the imports we saw: https://github.com/dotnet/try-convert/issues/295

We should probably also list out the ones that we expected. I'll edit that issue accordingly.
