### ISSUE TITLE
Error when more than one VS install is present

### ISSUE THREAD

**Issue by KSchlobohm** [dotnet/try-convert#395]
The error happens when running try-convert on a machine with more than one Visual Studio instance installed.

https://github.com/dotnet/try-convert/blob/18e164596c5fd5cfdf86f020734c3e884d475762/src/MSBuild.Conversion.SDK/TargetFrameworkHelper.cs#L25

From the console:
```
Unable to find the .NET SDK on this machine, manually pass '-tfm'
System.InvalidOperationException: Sequence contains more than one element
   at System.Linq.ThrowHelper.ThrowMoreThanOneElementException()
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
   at MSBuild.Conversion.SDK.TargetFrameworkHelper.FindHighestInstalledTargetFramework(Boolean usePreviewSDK) in C:\dev\try-convert\src\MSBuild.Conversion.SDK\TargetFrameworkHelper.cs:line 25
   at MSBuild.Conversion.Program.Run(String project, String workspace, String msbuildPath, String tfm, Boolean forceWebConversion, Boolean preview, Boolean diffOnly, Boolean noBackup, Boolean keepCurrentTfms) in C:\dev\try-convert\src\try-convert\Program.cs:line 82
```

**Comment by twsouthwick** [comment]
Ah! We should pass it the one we're using so there's consistency. Is there a command line option for that?
