### ISSUE TITLE
Try-convert breaks if the --msbuild-path ends with a trailing backslash

### ISSUE THREAD

**Issue by KSchlobohm** [dotnet/try-convert#398]
### Steps to repro
1. Create a new Console App for .NET Framework
2. run try-convert with the option to default --msbuild-path
` -m \"C:\Program Files\dotnet\sdk\5.0.202\"`

### Exception
```
System.AggregateException: A directory or directories in "msbuildSearchPaths" do not exist (Directory "C:\Program Files\dotnet\sdk\5.0.202"" does not exist (Parameter 'msbuildSearchPaths'))
 ---> System.ArgumentException: Directory "C:\Program Files\dotnet\sdk\5.0.202"" does not exist (Parameter 'msbuildSearchPaths')
   --- End of inner exception stack trace ---
   at Microsoft.Build.Locator.MSBuildLocator.RegisterMSBuildPath(String[] msbuildSearchPaths)
   at Microsoft.Build.Locator.MSBuildLocator.RegisterMSBuildPath(String msbuildPath)
   at MSBuild.Abstractions.MSBuildHelpers.HookAssemblyResolveForMSBuild(String msbuildPath) in C:\dev\try-convert\src\MSBuild.Abstractions\MSBuildHelpers.cs:line 392
   at MSBuild.Conversion.Program.Run(String project, String workspace, String msbuildPath, String tfm, Boolean forceWebConversion, Boolean preview, Boolean diffOnly, Boolean noBackup, Boolean keepCurrentTfms) in C:\dev\try-convert\src\try-convert\Program.cs:line 64

C:\dev\try-convert\artifacts\bin\try-convert\Debug\net5.0\try-convert.exe (process 9300) exited with code -1.
```

**Comment by KSchlobohm** [comment]
nm, I back slashed my way out of the problem that didn't exist.

my launch settings file didn't have enough...
```"commandLineArgs": "-p C:\\deleteme\\VbWpfApp1\\VbWpfApp1\\VbWpfApp1.vbproj -m \"C:\\Program Files\\dotnet\\sdk\\5.0.202\\\" --keep-current-tfms --force-web-conversion"```
