### ISSUE TITLE
seem to be able to fix this error

### ISSUE THREAD

**Issue by modz2014** [dotnet/try-convert#445]
System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
File name: 'System.Runtime, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at MSBuild.Abstractions.MSBuildConversionWorkspaceLoader.LoadWorkspace(String path, Boolean noBackup, String tfm, Boolean keepCurrentTFMs, Boolean forceWeb)
   at MSBuild.Conversion.Program.Run(String project, String workspace, String msbuildPath, String tfm, Boolean forceWebConversion, Boolean preview, Boolean diffOnly, Boolean noBackup, Boolean keepCurrentTfms, Boolean update, Boolean mauiConversion) in /_/src/try-convert/Program.cs:line 133

**Comment by MattBussing** [comment]
duplicate of #439

**Comment by modz2014** [comment]
I already did I didn't use nuget package

**Comment by MattBussing** [comment]
What version of VS and the dotnet sdk are you using?

**Comment by modz2014** [comment]
The latest one
