### ISSUE TITLE
Specifying Diff-Only on VB project cause failure

### ISSUE THREAD

**Issue by paul1956** [dotnet/try-convert#87]
If --Diff-Only is specified the Report can't be saved because the directory  Project.vbproj does not exist. It doesn't exist because its the Project file not a directory.

This could be related to lack of examples that show how -p and -w are used or my lack of understanding what --diff-only does. Below is the command line I used that worked when I removed --Diff-Only. Without -m it can't find MSBuild.
```
try-convert.exe -w "WordFinder\WordFinder.vbproj" -m "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\amd64"
```
Thanks the tool worked very well and is much simpler then doing it manually.

**Comment by cartermp** [comment]
Thanks @paul1956, interesting that it cannot find MSBuild unless you specify `-m` explicitly. Do you have a specialized install of VS? Typically is just find a binary under `MSBuild\Current` as a part of the standard VS 2019 install.

**Comment by paul1956** [comment]
I have VS 16.4.0 Preview 1, VS 16.3.1 PLUS standalone MSBuild 14
![image](https://user-images.githubusercontent.com/12789369/66343591-cc65b480-e900-11e9-93ad-28a56e94dd88.png)

**Comment by jmarolf** [comment]
If you don't provide a msbuild don't we ask which one you want to use? manually specifying it should only be necessary as a debug option

**Comment by paul1956** [comment]
Without MSBuild but with diff-only
```
C:\Users\PaulM\Desktop\FindWordApp1>try-convert.exe -w "WordFinder\WordFinder.vbproj" --diff-only
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\PaulM\Desktop\FindWordApp1\WordFinder\WordFinder.vbproj\report.txt'.
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.StreamWriter.ValidateArgsAndOpenPath(String path, Boolean append, Encoding encoding, Int32 bufferSize)
   at System.IO.StreamWriter..ctor(String path)
   at System.IO.File.WriteAllLines(String path, IEnumerable`1 contents)
   at MSBuild.Conversion.Project.Differ.GenerateReport(String reportFilePath) in C:\Users\PaulM\Source\Repos\try-convert\src\MSBuild.Conversion.Project\Differ.cs:line 115
   at MSBuild.Conversion.Program.Run(String project, String workspace, String msbuildPath, Boolean diffOnly, Boolean noBackup) in try-convert\src\try-convert\Program.cs:line 80
```

**Comment by cartermp** [comment]
This should do it: #93
