### ISSUE TITLE
Exception when trying to convert solution

### ISSUE THREAD

**Issue by khellang** [dotnet/try-convert#99]
When trying to convert [this solution](github.com/agolaszewski/Inquirer.cs/blob/2a06b08e2abb56da909295dd23fc8fa1bbd3f95f/Source/Inquirer.sln), I get the following exception:

```
$ try-convert -w Inquirer.sln
System.InvalidOperationException: Sequence contains more than one matching element
   at System.Linq.ThrowHelper.ThrowMoreThanOneMatchException()
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at MSBuild.Abstractions.MSBuildHelpers.GetOrCreatePackageReferencesItemGroup(IProjectRootElement rootElement) in /_/src/MSBuild.Abstractions/MSBuildHelpers.cs:line 257
   at MSBuild.Conversion.Project.ProjectRootElementExtensions.AddPackage(IProjectRootElement projectRootElement, String packageName, String packageVersion) in /_/src/MSBuild.Conversion.Project/ProjectRootElementExtensions.cs:line 293
   at MSBuild.Conversion.Project.ProjectRootElementExtensions.RemoveOrUpdateItems(IProjectRootElement projectRootElement, ImmutableDictionary`2 differs, BaselineProject baselineProject, String tfm) in /_/src/MSBuild.Conversion.Project/ProjectRootElementExtensions.cs:line 175
   at MSBuild.Conversion.Project.Converter.ConvertProjectFile() in /_/src/MSBuild.Conversion.Project/Converter.cs:line 69
   at MSBuild.Conversion.Project.Converter.Convert(String outputPath) in /_/src/MSBuild.Conversion.Project/Converter.cs:line 28
   at MSBuild.Conversion.Program.Run(String project, String workspace, String msbuildPath, Boolean diffOnly, Boolean noBackup) in /_/src/try-convert/Program.cs:line 85
```

**Comment by cartermp** [comment]
There's a very simple fix for this, but the core issue is that the project is kinda funky since it uses a nuget package that throws in custom imports. Basically everything gets thrown out the window when we're in that kind of world, since there's no way to guarantee that these will remain working on .NET Core. Looking at the source of the [StyleCop package ](https://github.com/StyleCop/StyleCop) used in the project, they don't support .NET Core.

**Comment by cartermp** [comment]
#102 tracks the real oddity in this solution; it turns out we can just convert it if we remove the imports that aren't necessary
